import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App1234',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <div style={{ position: 'absolute', bottom: '10px', left: '10px', fontSize: '12px', color: '#666' }}>
          本系统为音频管理系统，提供音频上传与浏览功能。
        </div>
      </body>
    </html>
  )
}